name: ceema
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  http: ^1.2.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.3.0
  grouped_list: ^6.0.0
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
